import { useState } from 'react'
import { Download, Copy, Check, FileText } from 'lucide-react'
import type { PyPIPackage, HealthScore } from '@/types'

interface MarkdownExportProps {
  packageData: PyPIPackage
  healthScore?: HealthScore
}

export function generateMarkdownReport(pkg: PyPIPackage, healthScore?: HealthScore): string {
  const { info } = pkg
  const releaseCount = Object.keys(pkg.releases).length

  let markdown = `# ${info.name}\n\n`
  
  // Description
  if (info.summary) {
    markdown += `> ${info.summary}\n\n`
  }

  // Quick Stats Table
  markdown += `## 📊 Quick Stats\n\n`
  markdown += `| Metric | Value |\n`
  markdown += `|--------|-------|\n`
  markdown += `| **Version** | ${info.version} |\n`
  markdown += `| **License** | ${info.license || 'Not specified'} |\n`
  markdown += `| **Python** | ${info.requires_python || 'Not specified'} |\n`
  markdown += `| **Releases** | ${releaseCount} |\n`
  if (info.maintainer) {
    markdown += `| **Maintainer** | ${info.maintainer} |\n`
  }
  if (info.author) {
    markdown += `| **Author** | ${info.author} |\n`
  }
  markdown += `\n`

  // Health Score
  if (healthScore) {
    const scoreEmoji = healthScore.score >= 80 ? '🟢' : healthScore.score >= 50 ? '🟡' : '🔴'
    markdown += `## 🏥 Health Score\n\n`
    markdown += `${scoreEmoji} **${healthScore.score}/100** (${healthScore.rating.toUpperCase()})\n\n`
    
    markdown += `### Breakdown\n\n`
    markdown += `- **Recency**: ${healthScore.breakdown.recency}/25\n`
    markdown += `- **Maintenance**: ${healthScore.breakdown.maintenance}/20\n`
    markdown += `- **Compatibility**: ${healthScore.breakdown.compatibility}/25\n`
    markdown += `- **Popularity**: ${healthScore.breakdown.popularity}/20\n`
    markdown += `- **Stability**: ${healthScore.breakdown.stability}/10\n\n`

    if (healthScore.warnings.length > 0) {
      markdown += `### ⚠️ Warnings\n\n`
      healthScore.warnings.forEach(warning => {
        markdown += `- ${warning}\n`
      })
      markdown += `\n`
    }

    if (healthScore.recommendations.length > 0) {
      markdown += `### 💡 Recommendations\n\n`
      healthScore.recommendations.forEach(rec => {
        markdown += `- ${rec}\n`
      })
      markdown += `\n`
    }
  }

  // Installation
  markdown += `## 📦 Installation\n\n`
  markdown += `\`\`\`bash\n`
  markdown += `# pip\npip install ${info.name}\n\n`
  markdown += `# Poetry\npoetry add ${info.name}\n\n`
  markdown += `# uv\nuv add ${info.name}\n\n`
  markdown += `# PDM\npdm add ${info.name}\n\n`
  markdown += `# Pipenv\npipenv install ${info.name}\n`
  markdown += `\`\`\`\n\n`

  // Dependencies
  if (info.requires_dist && info.requires_dist.length > 0) {
    markdown += `## 📋 Dependencies\n\n`
    markdown += `<details>\n`
    markdown += `<summary>Click to expand (${info.requires_dist.length} dependencies)</summary>\n\n`
    info.requires_dist.forEach(dep => {
      markdown += `- \`${dep}\`\n`
    })
    markdown += `\n</details>\n\n`
  }

  // Project URLs
  if (info.project_urls && Object.keys(info.project_urls).length > 0) {
    markdown += `## 🔗 Links\n\n`
    Object.entries(info.project_urls).forEach(([key, url]) => {
      markdown += `- [${key}](${url})\n`
    })
    markdown += `\n`
  }

  // Classifiers
  if (info.classifiers && info.classifiers.length > 0) {
    const topics = info.classifiers.filter(c => c.startsWith('Topic ::'))
    const intendedAudiences = info.classifiers.filter(c => c.startsWith('Intended Audience ::'))
    
    if (topics.length > 0 || intendedAudiences.length > 0) {
      markdown += `## 🏷️ Categories\n\n`
      if (topics.length > 0) {
        markdown += `**Topics**: ${topics.map(t => t.replace('Topic :: ', '').replace(/ :: /g, ' > ')).join(', ')}\n\n`
      }
      if (intendedAudiences.length > 0) {
        markdown += `**Audience**: ${intendedAudiences.map(a => a.replace('Intended Audience :: ', '')).join(', ')}\n\n`
      }
    }
  }

  // Footer
  markdown += `---\n\n`
  markdown += `*Generated by [PyPI Intelligence](https://pypi-intelligence.vercel.app) on ${new Date().toLocaleDateString()}*\n`

  return markdown
}

export function MarkdownExport({ packageData, healthScore }: MarkdownExportProps) {
  const [copied, setCopied] = useState(false)
  const markdown = generateMarkdownReport(packageData, healthScore)

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(markdown)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      console.error('Failed to copy')
    }
  }

  const downloadMarkdown = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${packageData.info.name}-report.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      <div
        className="rounded-lg border"
        style={{ backgroundColor: 'var(--card-bg)', borderColor: 'var(--border)' }}
      >
        <div
          className="flex items-center justify-between border-b px-4 py-3"
          style={{ borderColor: 'var(--border)' }}
        >
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5" style={{ color: 'var(--accent)' }} />
            <span className="font-medium" style={{ color: 'var(--text-primary)' }}>
              Markdown Report
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={copyToClipboard}
              className="flex items-center gap-2 rounded-lg bg-(--bg-tertiary) px-3 py-1.5 text-sm transition-colors hover:bg-(--accent-light)"
              style={{ color: 'var(--text-secondary)' }}
            >
              {copied ? (
                <>
                  <Check className="h-4 w-4" style={{ color: 'var(--success)' }} />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4" />
                  Copy
                </>
              )}
            </button>
            <button
              onClick={downloadMarkdown}
              className="flex items-center gap-2 rounded-lg bg-(--accent) px-3 py-1.5 text-sm font-medium text-white transition-colors hover:opacity-90"
            >
              <Download className="h-4 w-4" />
              Download
            </button>
          </div>
        </div>
        <pre
          className="max-h-96 overflow-auto p-4 text-sm"
          style={{
            backgroundColor: 'var(--bg-tertiary)',
            color: 'var(--text-secondary)',
            fontFamily: 'monospace',
          }}
        >
          {markdown}
        </pre>
      </div>
    </div>
  )
}

// Button component for easy integration
interface MarkdownExportButtonProps {
  packageData: PyPIPackage
  healthScore?: HealthScore
  variant?: 'default' | 'outline'
  size?: 'sm' | 'md' | 'lg'
}

export function MarkdownExportButton({
  packageData,
  healthScore,
  variant = 'default',
  size = 'md',
}: MarkdownExportButtonProps) {
  const [showModal, setShowModal] = useState(false)

  const sizeClasses = {
    sm: 'px-2 py-1 text-xs',
    md: 'px-3 py-1.5 text-sm',
    lg: 'px-4 py-2 text-base',
  }

  const variantClasses = {
    default: 'bg-(--accent) text-white hover:opacity-90',
    outline: 'border border-(--accent) text-(--accent) hover:bg-(--accent-light)',
  }

  return (
    <>
      <button
        onClick={() => setShowModal(true)}
        className={`flex items-center gap-2 rounded-lg transition-colors ${sizeClasses[size]} ${variantClasses[variant]}`}
      >
        <FileText className={size === 'sm' ? 'h-3 w-3' : 'h-4 w-4'} />
        Export Markdown
      </button>

      {showModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
          onClick={() => setShowModal(false)}
        >
          <div
            className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl"
            style={{ backgroundColor: 'var(--bg-primary)' }}
            onClick={e => e.stopPropagation()}
          >
            <div
              className="flex items-center justify-between border-b p-4"
              style={{ borderColor: 'var(--border)' }}
            >
              <h3 className="text-lg font-semibold" style={{ color: 'var(--text-primary)' }}>
                Export Package Report
              </h3>
              <button
                onClick={() => setShowModal(false)}
                className="rounded p-1 transition-colors hover:bg-(--bg-tertiary)"
              >
                <svg className="h-5 w-5" style={{ color: 'var(--text-muted)' }} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="p-4">
              <MarkdownExport packageData={packageData} healthScore={healthScore} />
            </div>
          </div>
        </div>
      )}
    </>
  )
}
